server:
  port: 8001


spring:
  application:
    name: cloud-pay-service
  datasource:
    #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.85.6:3306/cloud-lean?useUnicode=true&characterEnconding=utf-8&useSSL=false
    username: ldap
    password: ldap


eureka:
  client:

    # 是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为true
    # 注意：单节点配置无所谓，但是集群必须设置为true 才能配合ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版
#      defaultZone: http://localhost:7001/eureka/
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: pay-8001
    # 在注册中心鼠标移上去可以显示微服务地址
    prefer-ip-address: true
    # Eureka 客户端向服务端发送心跳的间隔时间，单位秒 默认是 30秒
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务端在收到最后一次心跳后的等待上线，单位为秒 默认为 90秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 2


mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 所有Entity 别名所在包
  type-aliases-package: com.atgg.leancloud.common.entities




