server:
  port: 9001

spring:
  application:
    name: cloudalibab-nacos-provider
  cloud:
    nacos:  # 配置 nacos 信息
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"