server:
  port: 9527
spring:
  application:
    name: cloud-gateway
# 原始的写死的地址
#  cloud:
#    gateway:
#      routes:
#        - id: pay_routh  # 路由的id，没有固定的规则，但是要求唯一，建议配合服务名
#          uri: http://localhost:8081 # 匹配后提供服务的路由地址
#          predicates:
#            - Path=/api/getPay/**   # 断言路径相匹配的进行路由
#        - id: pay_routh2 # 路由的id
#          uri: http://localhost:8001
#          predicates:
#            - Path=/api/pay/getPayInfo/**
# 开启动态路由,实现负载均衡
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pay_routh
          uri: lb://cloud-pay-service
          predicates:
            - Path=/api/getPay/**
        - id: pay_routh2
          uri: lb://cloud-pay-service
          predicates:
            - Path=/api/pay/getPayInfo/
        - id: pay_routh3
          uri: lb://cloud-pay-service
          predicates:
             - Path=/api/pay/getport/
             - After=2020-04-07T19:08:22.448+08:00[Asia/Shanghai] # 在这个时间之后才能访问
eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway-8501
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/



